#!/usr/bin/env python3
"""Probe every target on every board against a live Prometheus.

Every target is run TWICE, because `or vector(0)` makes a single check useless in
both directions:

  shipped  the expression exactly as the panel runs it. An expression ending in
           `or vector(0)` ALWAYS returns a row, so this proves only that the panel
           does not ERROR -- never that the metric exists.
  strict   the same expression with the `or vector(0)` fallbacks removed. This is
           what proves the underlying series is real.

Each target lands in one of four states:

  OK        both modes return data. The series exists and the panel renders it.
  FALLBACK  shipped returns data, strict does not. The panel renders (usually 0)
            off its `or vector(0)`, because the series genuinely has not been
            created yet. This is EXPECTED for anything that only appears once
            something goes wrong -- failures, timeouts, cancellations,
            non-determinism -- and it is the correct design: a blank panel reads
            as "broken", a zero reads as "healthy".
  NODATA    neither mode returns data and there is no fallback. Either the stack
            is not in the state this panel needs, or the metric name is WRONG.
            Check it against docs/DASHBOARDS.md, "Proving the boards".
  ERROR     Prometheus rejected the query. Always a bug in the expression.

Note that FALLBACK is not a weaker OK. Core creates a metric on FIRST INCREMENT,
so a counter that has never fired is absent from /metrics entirely rather than
reading 0 -- which is exactly why those fallbacks are load-bearing here in a way
they were not in the Go original.

--------------------------------------------------------------------------
TWO KINDS OF BOARD, PROBED FOR TWO DIFFERENT REASONS
--------------------------------------------------------------------------
  authored  dashboards/sandbox/*.json, generated by build-dashboards.py. Ours, so
            a NODATA or an ERROR here is a bug to go fix. The exit code reflects
            ONLY these.
  vendored  dashboards/temporal-sdk/ and dashboards/temporal-server/, copied from
            temporalio/dashboards at the SHA in dashboards/UPSTREAM_SHA. Probing
            these is how "leave all three PrometheusOptions suffix flags false,
            because that is what the vendored Core SDK board is written against"
            stops being an assertion and becomes a measurement: that board
            expects bare counter names and millisecond histograms, so if the
            premise were wrong its panels would go NODATA in a block.
            OFF BY DEFAULT, and never a build failure. Upstream writes these
            against a fully loaded multi-namespace cluster with Nexus, schedules,
            archival and visibility all in play; a laptop sandbox leaves plenty
            of their panels legitimately empty. Informative, not a contract.

Usage:
  python3 probe-dashboards.py                  # the authored sandbox boards
  python3 probe-dashboards.py worker signals   # named boards, by file stem
  python3 probe-dashboards.py --vendored       # the three upstream boards
  python3 probe-dashboards.py --all            # both
"""

import json
import pathlib
import re
import sys
import urllib.parse
import urllib.request

PROM = "http://localhost:9090"
HERE = pathlib.Path(__file__).resolve().parent
DASHBOARDS = HERE / "dashboards"
AUTHORED = DASHBOARDS / "sandbox"
VENDORED = (DASHBOARDS / "temporal-sdk", DASHBOARDS / "temporal-server")

# Grafana-only macros Prometheus does not understand. $__rate_interval is what
# Grafana computes from the datasource's timeInterval; 1m is a safe stand-in for a
# probe. Template variables are pinned to the values the sandbox actually uses.
# The vendored boards need nothing extra here: they use only $__rate_interval and
# $namespace in expressions ($Service and $Client appear in panel TITLES only).
SUBS = [
    (r"\$__rate_interval", "1m"),
    (r"\$__interval", "1m"),
    (r"\$__range", "15m"),
    (r"\$namespace", "default"),
    (r"\$task_queue", "repro-task-queue"),
]


def query(expr):
    url = f"{PROM}/api/v1/query?" + urllib.parse.urlencode({"query": expr})
    with urllib.request.urlopen(url, timeout=15) as r:   # noqa: S310
        return json.load(r)


def resolve(expr):
    for pattern, value in SUBS:
        expr = re.sub(pattern, value, expr)
    return expr


def strip_or_vector(expr):
    """Remove trailing `or vector(0)` so a panel cannot pass on its own fallback."""
    return re.sub(r"\s+or\s+vector\(0\)", "", expr)


def walk(panels):
    """Yield every panel, INCLUDING the ones nested inside row panels.

    The authored boards are flat. Upstream's are not: history-service.json and
    server-general.json park most of their panels inside collapsed rows, so a
    flat iteration probes a third of the board and then reports a clean run.
    """
    for p in panels:
        yield p
        yield from walk(p.get("panels") or [])


def panel_targets(panel):
    for target in panel.get("targets") or []:
        expr = (target.get("expr") or "").strip()
        # Row and text panels have no targets at all. Upstream also ships a couple
        # of targets with an EMPTY expr, which Prometheus rejects with a parse
        # error rather than answering "nothing" -- that would score as ERROR and
        # read as a bug in a board we did not write. Hidden targets do not render,
        # so they are not evidence either way.
        if not expr or target.get("hide"):
            continue
        yield panel.get("title") or "(untitled)", expr


def classify(raw):
    """Return (state, detail) for one target."""
    expr = resolve(raw)
    bare = strip_or_vector(expr)

    def usable(result):
        rows = result["data"]["result"]
        return [r for r in rows
                if r.get("value") and r["value"][1] not in ("NaN", "+Inf", "-Inf")]

    try:
        shipped = query(expr)
    except Exception as exc:                              # noqa: BLE001
        return "ERROR", str(exc)
    if shipped.get("status") != "success":
        return "ERROR", shipped.get("error", "")

    shipped_rows = usable(shipped)

    if bare == expr:
        return ("OK", f"{len(shipped_rows)} series") if shipped_rows else ("NODATA", "no series")

    try:
        strict = query(bare)
    except Exception as exc:                              # noqa: BLE001
        return "ERROR", str(exc)
    if strict.get("status") != "success":
        return "ERROR", strict.get("error", "")

    if usable(strict):
        return "OK", f"{len(usable(strict))} series"
    if shipped_rows:
        return "FALLBACK", "renders via `or vector(0)`; series not created yet"
    return "NODATA", "no series and no fallback"


def probe(board, verbose=True):
    """Probe one board. Returns (target tally, panels with targets, panels that render)."""
    tally = {"OK": 0, "FALLBACK": 0, "NODATA": 0, "ERROR": 0}
    panels = rendering = 0
    doc = json.loads(board.read_text())
    for panel in walk(doc.get("panels", [])):
        rows = list(panel_targets(panel))
        if not rows:
            continue
        panels += 1
        lit = False
        for title, raw in rows:
            state, detail = classify(raw)
            tally[state] += 1
            lit = lit or state in ("OK", "FALLBACK")
            if not verbose:
                continue
            if state == "OK":
                print(f"  OK        {title}  ({detail})")
            else:
                print(f"  {state:9s} {title}  [{detail}]")
                if state in ("NODATA", "ERROR"):
                    print(f"            {resolve(raw)[:150]}")
        rendering += lit
    return tally, panels, rendering


def summarize(label, tally, panels, rendering):
    total = sum(tally.values())
    print(f"\n{label}: {tally['OK']} OK  +  {tally['FALLBACK']} FALLBACK  "
          f"=  {tally['OK'] + tally['FALLBACK']}/{total} targets render")
    print(f"{label}: {tally['NODATA']} NODATA, {tally['ERROR']} ERROR")
    print(f"{label}: {rendering}/{panels} panels have at least one series")


def main():
    flags = {a for a in sys.argv[1:] if a.startswith("-")}
    wanted = [a for a in sys.argv[1:] if not a.startswith("-")]
    do_vendored = bool(flags & {"--vendored", "--all"})
    do_authored = "--all" in flags or "--vendored" not in flags

    files = []
    if do_authored:
        files += [("authored", f) for f in sorted(AUTHORED.glob("*.json"))]
    if do_vendored:
        for d in VENDORED:
            files += [("vendored", f) for f in sorted(d.glob("*.json"))]
    if wanted:
        files = [(kind, f) for kind, f in files if f.stem in wanted]

    totals = {}
    for kind, board in files:
        print(f"\n=== {board.stem} [{kind}] ===")
        tally, panels, rendering = probe(board)
        agg = totals.setdefault(kind, ({"OK": 0, "FALLBACK": 0, "NODATA": 0, "ERROR": 0}, [0, 0]))
        for k, v in tally.items():
            agg[0][k] += v
        agg[1][0] += panels
        agg[1][1] += rendering

    for kind, (tally, (panels, rendering)) in totals.items():
        summarize(kind, tally, panels, rendering)

    # Vendored boards are upstream's, pinned at a SHA, and not ours to fix -- their
    # NODATA is a statement about this sandbox's workload, not about this repo.
    # Only the authored boards gate the exit code.
    return 1 if totals.get("authored", ({"ERROR": 0}, None))[0]["ERROR"] else 0


if __name__ == "__main__":
    sys.exit(main())
