using System.Text;
using Repro.Core;
using Repro.Core.Activities;
using Temporalio.Converters;
using Xunit;

namespace Repro.Tests;

/// <summary>
/// The pure statics <c>FileScanActivities</c> exposes, and the corpus arithmetic the resume path
/// rests on.
/// </summary>
/// <remarks>Every failure covered here is silent: a malformed row parsed as a plausible index
/// drifts the byte cursor, and a checkpoint that disagrees with itself or comes from another
/// corpus reports a wrong total as <c>outcome="completed"</c>. Nothing here opens
/// <c>sample_files/</c>; see <see cref="Rows100Mb"/>.</remarks>
public class FileScanActivitiesTests
{
    // Corpus constants, duplicated by hand from scripts/gen-samples/MANIFEST.txt.

    /// <summary>Rows in <c>sample-100mb.txt</c>, per scripts/gen-samples/MANIFEST.txt.</summary>
    /// <remarks>Duplicated by hand: sample_files/ is gitignored, generated by
    /// scripts/gen-samples/gen-samples.sh, and absent on a fresh clone, so no test here reads the
    /// corpus. Keep in step with MANIFEST.txt by hand.
    /// <c>ConfigLoader.LargestShippedCorpusRows</c> is a third copy of this row.</remarks>
    private const long Rows100Mb = 1_724_588;

    /// <inheritdoc cref="Rows100Mb"/>
    private const long Bytes100Mb = 99_999_968;

    /// <summary>digits(<see cref="Rows100Mb"/>) + 1, the length of line 1 including its LF.</summary>
    private const int Header100Mb = 8;

    /// <summary><see cref="Rows100Mb"/> x (<see cref="Rows100Mb"/> + 1) / 2, at a full scan.</summary>
    /// <remarks>The number the idempotency verdict is decided on, also a literal in
    /// FileScanJob.cs, config.yaml and docs/WORKFLOWS.md.</remarks>
    private const long IndexSum100Mb = 1_487_102_747_166;

    /// <summary><see cref="Bytes100Mb"/> - <see cref="Header100Mb"/> - 20 x <see cref="Rows100Mb"/>.</summary>
    private const long WordByteSum100Mb = 65_508_200;

    /// <summary><c>sample-200mb.txt</c>, the nearest neighbour a stale checkpoint can come from.</summary>
    /// <inheritdoc cref="Rows100Mb"/>
    private const long Rows200Mb = 3_449_054;

    /// <inheritdoc cref="Rows200Mb"/>
    private const long Bytes200Mb = 199_999_981;

    /// <summary>A mid-scan row on the 100 MB corpus.</summary>
    private const long MidRows = 611_402;

    /// <inheritdoc cref="MidRows"/>
    private const long MidByteOffset = 35_461_940;

    /// <summary><see cref="MidByteOffset"/> - <see cref="Header100Mb"/> - 20 x <see cref="MidRows"/>.</summary>
    private const long MidWordByteSum = 23_233_892;

    /// <summary><see cref="MidRows"/> x (<see cref="MidRows"/> + 1) / 2.</summary>
    private const long MidIndexSum = 186_906_508_503;

    /// <summary>A fixed, non-default heartbeat timestamp.</summary>
    /// <remarks>Sub-second ticks on purpose: truncation to whole seconds would pass a test
    /// written against a whole second. Never <c>default</c>, which
    /// <c>CheckpointDisagreement</c> treats as an unbound parameter.</remarks>
    private static readonly DateTimeOffset Recorded =
        new DateTimeOffset(2026, 9, 2, 10, 43, 17, TimeSpan.Zero).AddTicks(1_234_567);

    /// <summary>A checkpoint the shipped 100 MB scan really could have written, mid-file.</summary>
    /// <remarks>Named arguments: six longs in a row, three large and plausible at the same
    /// magnitude, so a positional construction compiles clean and means something else.</remarks>
    private static FileScanCheckpoint MidScan() => new(
        Rows: MidRows,
        ByteOffset: MidByteOffset,
        IndexSum: MidIndexSum,
        WordByteSum: MidWordByteSum,
        FileRows: Rows100Mb,
        FileBytes: Bytes100Mb,
        RecordedAtUtc: Recorded);

    /// <summary>The checkpoint an attempt writes after reading the last row of the corpus.</summary>
    /// <remarks>Reachable: an attempt killed after heartbeating row N leaves this. It is the
    /// boundary <c>CorpusDisagreement</c>'s <c>&lt;=</c> comparisons exist for.</remarks>
    private static FileScanCheckpoint FullScan() => new(
        Rows: Rows100Mb,
        ByteOffset: Bytes100Mb,
        IndexSum: IndexSum100Mb,
        WordByteSum: WordByteSum100Mb,
        FileRows: Rows100Mb,
        FileBytes: Bytes100Mb,
        RecordedAtUtc: Recorded);

    // ParseRowIndex: the per-row hot path, and the byte cursor's only structural guard.

    /// <summary>A well-formed row yields its own 1-based index.</summary>
    /// <remarks>The LF is excluded, as the read loop slices the row from between two line breaks.
    /// A parser that stopped at the first non-zero digit gets row 1 right and row N wrong.</remarks>
    [Theory]
    [InlineData("0000000001 [ab abc abcd abcde ab abc abcd]", 1L)]
    [InlineData("0000000005 [aa bb cc dd ee ff gg]", 5L)]
    [InlineData("0000611402 [aa bb cc dd ee ff gg]", 611_402L)]
    [InlineData("0001724588 [aa bb cc dd ee ff gg]", 1_724_588L)]
    [InlineData("9999999999 [aa bb cc dd ee ff gg]", 9_999_999_999L)]
    public void ParsesAWellFormedRow(string row, long expected) =>
        Assert.Equal(expected, FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes(row)));

    /// <summary>Every structurally wrong shape returns the sentinel, never a plausible index.</summary>
    /// <remarks>A tolerated malformed row is silent: the accumulator is
    /// <c>rowLength + 1 - RowOverhead</c> whatever the row contains, so the cursor keeps moving
    /// and the only symptom is a resume that lands mid-row. The read loop splits on LF, so on a
    /// CRLF corpus the last byte of every row is <c>\r</c>; tolerating it drifts the cursor one
    /// byte per row, and only the <c>\r</c>, <c>\n</c> and <c>}</c> rows here see the
    /// <c>row[^1] != ']'</c> clause go.</remarks>
    [Theory]
    // Below the structural floor of 10 digits + ' ' + '[' + ']'.
    [InlineData("")]
    [InlineData("0000000001")]
    [InlineData("0000000001 [")]
    // The separator: a tab is whitespace to long.TryParse and nothing to the corpus contract.
    [InlineData("0000000001\t[aa bb cc]")]
    [InlineData("0000000001_[aa bb cc]")]
    // The opening bracket.
    [InlineData("0000000001 (aa bb cc)")]
    [InlineData("0000000001  aa bb cc]")]
    // The closing bracket, CRLF first: this is why the last byte is checked. The LF row pins the
    // other half of the contract, that a row excludes its own LF.
    [InlineData("0000000001 [aa bb cc]\r")]
    [InlineData("0000000001 [aa bb cc]\n")]
    [InlineData("0000000001 [aa bb cc}")]
    // The digits. long.TryParse accepts a sign and a leading space, which the corpus contract
    // forbids, so ParseDigits is hand-rolled.
    [InlineData("000000000O [aa bb cc]")]
    [InlineData("+000000001 [aa bb cc]")]
    [InlineData("-000000001 [aa bb cc]")]
    [InlineData(" 000000001 [aa bb cc]")]
    // An 11-digit index: the space lands one byte late.
    [InlineData("00000000012 [aa bb cc]")]
    public void RejectsAMalformedRow(string row) =>
        Assert.Equal(
            FileScanActivities.MalformedRow,
            FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes(row)));

    /// <summary>A row with no words at all is legal: the floor is the structural minimum, not
    /// <c>RowOverhead</c>.</summary>
    [Fact]
    public void AcceptsTheShortestStructurallyLegalRow() =>
        Assert.Equal(1L, FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes("0000000001 []")));

    /// <summary>The sentinel must stay outside the range of any real row index.</summary>
    /// <remarks>Row indices are 1-based, so a sentinel of 0 would let the resume path's
    /// row-identity proof accept a malformed row as row 0.</remarks>
    [Fact]
    public void TheMalformedSentinelCannotBeARowIndex() =>
        Assert.True(FileScanActivities.MalformedRow < 1);

    // HeaderLength: the one input to the byte identity that is derived rather than carried.

    /// <summary>digits(N) + 1, including the digit boundaries on both sides.</summary>
    /// <remarks>Both plausible off-by-ones in <c>for (r = fileRows; r >= 10; r /= 10)</c> are
    /// right on a mid-decade number and wrong at exactly one power of ten, and one byte of error
    /// in <c>headerLen</c> rejects every legitimate checkpoint as terminal. Changing
    /// <c>&gt;= 10</c> to <c>&gt; 10</c> fails only the powers of ten; all four shipped-corpus
    /// rows still pass.</remarks>
    [Theory]
    [InlineData(1L, 2)]
    [InlineData(9L, 2)]
    [InlineData(10L, 3)]
    [InlineData(11L, 3)]
    [InlineData(99L, 3)]
    [InlineData(100L, 4)]
    [InlineData(999L, 4)]
    [InlineData(1000L, 5)]
    [InlineData(999_999L, 7)]
    [InlineData(1_000_000L, 8)]
    // All four shipped corpora are 7 digits, which is why the corpus discriminator is
    // (fileRows, fileBytes) and not the header length.
    [InlineData(Rows100Mb, 8)]
    [InlineData(Rows200Mb, 8)]
    [InlineData(6_035_691L, 8)]
    [InlineData(8_622_570L, 8)]
    public void HeaderLengthIsDigitsPlusTheLineFeed(long fileRows, int expected) =>
        Assert.Equal(expected, FileScanActivities.HeaderLength(fileRows));

    /// <summary>Zero rows still costs a digit and an LF, so the seek-back cannot go negative.</summary>
    /// <remarks>The line-boundary proof seeks to <c>ByteOffset - 1</c>, kept non-negative by
    /// <c>ByteOffset &gt;= headerLen &gt;= 2</c>.</remarks>
    [Fact]
    public void HeaderLengthIsNeverBelowTwo() =>
        Assert.Equal(2, FileScanActivities.HeaderLength(0));

    // CheckpointDisagreement: no I/O, everything it checks is carried in the checkpoint.

    /// <summary>A checkpoint the scan really wrote passes, mid-file and at the end.</summary>
    [Fact]
    public void AcceptsASelfConsistentCheckpoint()
    {
        Assert.Null(FileScanActivities.CheckpointDisagreement(MidScan()));
        Assert.Null(FileScanActivities.CheckpointDisagreement(FullScan()));
    }

    /// <summary>Row 0 at the header offset is self-consistent, and must not need a special
    /// case.</summary>
    [Fact]
    public void AcceptsTheZeroRowCheckpoint() =>
        Assert.Null(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: 0,
            ByteOffset: Header100Mb,
            IndexSum: 0,
            WordByteSum: 0,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));

    /// <summary>The schema-drift signature: a zeroed IndexSum beside a correct ByteOffset.</summary>
    /// <remarks>Heartbeat details bind by name through the data converter, so renaming a
    /// <c>FileScanCheckpoint</c> parameter yields <c>default(T)</c> for it while every other
    /// field arrives correct. The resume then seeks to a real line boundary and the scan
    /// completes short by the rows before the checkpoint; the only other symptom is
    /// <c>repro_file_scan_verified{result="mismatch"}</c> five minutes later.</remarks>
    [Fact]
    public void RejectsAZeroedIndexSumBesideACorrectByteOffset()
    {
        var drifted = MidScan() with { IndexSum = 0 };

        // The byte cursor still agrees with itself, which is what makes this silent.
        Assert.Equal(
            FileScanActivities.HeaderLength(drifted.FileRows)
                + (FileScanActivities.RowOverhead * drifted.Rows)
                + drifted.WordByteSum,
            drifted.ByteOffset);

        var why = FileScanActivities.CheckpointDisagreement(drifted);

        Assert.NotNull(why);
        Assert.Contains("indexSum", why!, StringComparison.Ordinal);
    }

    /// <summary>A zeroed FileRows or FileBytes is the same unbound-parameter failure.</summary>
    [Fact]
    public void RejectsACheckpointWithNoCorpusIdentity()
    {
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileRows = 0 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileBytes = 0 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileRows = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileBytes = -1 }));
    }

    /// <summary>None of the three accumulators may be negative.</summary>
    [Fact]
    public void RejectsNegativeAccumulators()
    {
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { Rows = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { WordByteSum = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { IndexSum = -1 }));

        // The one that survives a byte-identity-only check: 8 + (20 x 0) + (-1) = 7, so the seek
        // lands at byte 6 of a file whose first row starts at byte 8.
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: 0,
            ByteOffset: Header100Mb - 1,
            IndexSum: 0,
            WordByteSum: -1,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));
    }

    /// <summary>A scan cannot have completed more rows than its own header declares.</summary>
    [Fact]
    public void RejectsMoreCompletedRowsThanTheCorpusHas() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: Rows100Mb + 1,
            ByteOffset: Bytes100Mb + 20,
            IndexSum: (Rows100Mb + 1) * (Rows100Mb + 2) / 2,
            WordByteSum: WordByteSum100Mb,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));

    /// <summary>The byte identity, <c>ByteOffset == headerLen + 20 x Rows + WordByteSum</c>:
    /// one byte of drift in either direction is refused.</summary>
    [Theory]
    [InlineData(1L)]
    [InlineData(-1L)]
    [InlineData(20L)]
    public void RejectsAByteOffsetThatDisagreesWithItsOwnRowCount(long drift)
    {
        var why = FileScanActivities.CheckpointDisagreement(
            MidScan() with { ByteOffset = MidByteOffset + drift });

        Assert.NotNull(why);
        Assert.Contains("byte offset", why!, StringComparison.Ordinal);
    }

    /// <summary>The row identity: an IndexSum that is not the closed form for its own row count.
    /// The accumulator's origin and the read cursor's origin must be one checkpoint.</summary>
    [Theory]
    [InlineData(1L)]
    [InlineData(-1L)]
    [InlineData(611_402L)]  // off by one row's worth: a resume that counted its landing row twice
    public void RejectsAnIndexSumThatIsNotTheClosedForm(long drift) =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(
            MidScan() with { IndexSum = MidIndexSum + drift }));

    /// <summary>A default RecordedAtUtc is refused, and the cost is the staleness histogram.</summary>
    /// <remarks><c>default(DateTimeOffset)</c> is year 1, so every sample lands in
    /// <c>repro_file_scan_staleness</c>' <c>+Inf</c> and the 24s shoulder is gone.</remarks>
    [Fact]
    public void RejectsACheckpointWithNoTimestamp() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(
            MidScan() with { RecordedAtUtc = default }));

    /// <summary>An all-default checkpoint, what a wholly unbound payload yields, is refused.</summary>
    [Fact]
    public void RejectsTheAllDefaultCheckpoint() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint()));

    // CorpusDisagreement: the checkpoint also has to be about the file that is now open, and
    // inside this invocation's bounds.

    /// <summary>
    /// The plausible wrong answer: a self-consistent 200 MB checkpoint against the 100 MB file.
    /// </summary>
    /// <remarks>The checkpoint below is what a scan of sample-200mb.txt writes at row 1,200,000,
    /// and it passes <c>CheckpointDisagreement</c> completely: self-consistency cannot see a
    /// corpus swap, and both corpora even have a 7-digit header. Unchecked, the resume lands on a
    /// valid line boundary, the row-identity proof passes because it is a property of the offset,
    /// and the scan reports <c>outcome="completed"</c> over a mixture of two files.</remarks>
    [Fact]
    public void RejectsASelfConsistentCheckpointFromADifferentCorpus()
    {
        var from200Mb = new FileScanCheckpoint(
            Rows: 1_200_000,
            ByteOffset: 69_576_008,
            IndexSum: 720_000_600_000,
            WordByteSum: 45_576_000,
            FileRows: Rows200Mb,
            FileBytes: Bytes200Mb,
            RecordedAtUtc: Recorded);

        // Self-consistent, and therefore invisible to every check that needs no file.
        Assert.Null(FileScanActivities.CheckpointDisagreement(from200Mb));

        // It also lands inside the smaller corpus, so a bounds check alone would pass it.
        Assert.True(from200Mb.ByteOffset < Bytes100Mb);

        var why = FileScanActivities.CorpusDisagreement(
            from200Mb, "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb);

        Assert.NotNull(why);

        Assert.Contains("/corpus/sample-100mb.txt", why!, StringComparison.Ordinal);
        Assert.Contains("3449054", why!, StringComparison.Ordinal);
        Assert.Contains("1724588", why!, StringComparison.Ordinal);
    }

    /// <summary>The matching corpus is accepted, mid-scan and at the last row.</summary>
    /// <remarks>The last-row case is why the bounds are <c>&lt;=</c>; rejecting it would fail the
    /// workflow terminally for having finished.</remarks>
    [Fact]
    public void AcceptsACheckpointForTheFileThatIsOpen()
    {
        Assert.Null(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));

        Assert.Null(FileScanActivities.CorpusDisagreement(
            FullScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));
    }

    /// <summary>Either half of the identity pair is enough to refuse the resume: a truncated or
    /// appended file changes only one of the two numbers.</summary>
    [Fact]
    public void RejectsAMismatchInEitherHalfOfTheCorpusIdentity()
    {
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/x.txt", Rows100Mb + 1, Bytes100Mb, Rows100Mb));

        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/x.txt", Rows100Mb, Bytes100Mb + 1, Rows100Mb));
    }

    /// <summary>A checkpoint written under a larger maxRows is a different job.</summary>
    [Fact]
    public void RejectsACheckpointFromALargerJob() =>
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, rowsToScan: 500_000));

    /// <summary>An offset past EOF on a file whose identity matched is still refused, or the
    /// loop reads zero bytes and blames the file for the checkpoint.</summary>
    [Fact]
    public void RejectsAnOffsetPastTheEndOfAMatchingFile()
    {
        // Self-consistent by construction: the extra word bytes are carried in the offset.
        var past = new FileScanCheckpoint(
            Rows: Rows100Mb,
            ByteOffset: Bytes100Mb + 1000,
            IndexSum: IndexSum100Mb,
            WordByteSum: WordByteSum100Mb + 1000,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded);

        Assert.Null(FileScanActivities.CheckpointDisagreement(past));
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            past, "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));
    }

    // The three closed forms, against the committed corpus numbers.

    /// <summary><c>IndexSum == N x (N + 1) / 2</c> for the shipped 100 MB corpus.</summary>
    /// <remarks>Makes a MANIFEST.txt regeneration that changes N a test failure rather than four
    /// stale literals. N x (N + 1) is 2.97e12: fine in <c>long</c>, wrapping in <c>int</c>.</remarks>
    [Fact]
    public void TheFullScanIndexSumIsTheDocumentedConstant() =>
        Assert.Equal(IndexSum100Mb, Rows100Mb * (Rows100Mb + 1) / 2);

    /// <summary><c>WordByteSum == FileBytes - HeaderLen - 20 x N</c>, written through
    /// <c>HeaderLength</c> and <c>RowOverhead</c> rather than the literals 8 and 20.</summary>
    [Fact]
    public void TheFullScanWordByteSumIsTheDocumentedConstant() =>
        Assert.Equal(
            WordByteSum100Mb,
            Bytes100Mb
                - FileScanActivities.HeaderLength(Rows100Mb)
                - (FileScanActivities.RowOverhead * Rows100Mb));

    /// <summary>The offset identity, at completion and mid-scan.</summary>
    [Fact]
    public void TheOffsetIdentityHoldsAtEveryCheckpoint()
    {
        Assert.Equal(
            Bytes100Mb,
            FileScanActivities.HeaderLength(Rows100Mb)
                + (FileScanActivities.RowOverhead * Rows100Mb)
                + WordByteSum100Mb);

        Assert.Equal(
            MidByteOffset,
            FileScanActivities.HeaderLength(Rows100Mb)
                + (FileScanActivities.RowOverhead * MidRows)
                + MidWordByteSum);
    }

    /// <summary>The fixed row overhead is the <c>ROW_OVERHEAD</c> gen_samples.py writes, and the
    /// coefficient in both identities above.</summary>
    [Fact]
    public void RowOverheadMatchesTheGenerator()
    {
        Assert.Equal(20, FileScanActivities.RowOverhead);
        Assert.Equal(10, FileScanActivities.IndexDigits);
    }

    // The data converter, pinned rather than argued.

    /// <summary>A checkpoint survives the default payload converter, field for field.</summary>
    /// <remarks>A converter failure on heartbeat details arrives as a cancellation, not an error:
    /// it cancels with <c>ActivityCancelReason.HeartbeatRecordFailure</c>, which looks like the
    /// worker drain this case does on purpose.</remarks>
    [Fact]
    public void ACheckpointRoundTripsThroughTheDefaultConverter()
    {
        var converter = DataConverter.Default.PayloadConverter;
        var before = MidScan();

        var after = converter.ToValue<FileScanCheckpoint>(converter.ToPayload(before));

        // Record equality is structural, so this covers all seven fields at once.
        Assert.Equal(before, after);

        // And it must stay resumable: this is what fails if the converter truncates a long or
        // drops sub-second ticks.
        Assert.Null(FileScanActivities.CheckpointDisagreement(after));
        Assert.Equal(Recorded, after.RecordedAtUtc);
    }

    /// <summary>A renamed parameter binds nothing, yields default(T), and is caught.</summary>
    /// <remarks><see cref="RejectsAZeroedIndexSumBesideACorrectByteOffset"/> driven through the
    /// real converter: the payload carries <c>IndexSumTotal</c> where the record declares
    /// <c>IndexSum</c>, and the converter raises nothing.</remarks>
    [Fact]
    public void ARenamedParameterBindsNothingAndTheDriftCheckCatchesIt()
    {
        var converter = DataConverter.Default.PayloadConverter;

        var drifted = converter.ToValue<FileScanCheckpoint>(converter.ToPayload(new
        {
            Rows = MidRows,
            ByteOffset = MidByteOffset,
            IndexSumTotal = MidIndexSum,   // <- the rename
            WordByteSum = MidWordByteSum,
            FileRows = Rows100Mb,
            FileBytes = Bytes100Mb,
            RecordedAtUtc = Recorded,
        }));

        // Without these, a converter that bound nothing would pass the assertion below.
        Assert.Equal(MidRows, drifted.Rows);
        Assert.Equal(MidByteOffset, drifted.ByteOffset);
        Assert.Equal(MidWordByteSum, drifted.WordByteSum);
        Assert.Equal(Rows100Mb, drifted.FileRows);
        Assert.Equal(Bytes100Mb, drifted.FileBytes);
        Assert.Equal(Recorded, drifted.RecordedAtUtc);

        Assert.Equal(0L, drifted.IndexSum);

        Assert.NotNull(FileScanActivities.CheckpointDisagreement(drifted));
    }

    /// <summary>The result record round-trips too, since it is a replay-visible schema.</summary>
    /// <remarks>An activity return value lands in history and is read back on replay, so its
    /// shape is a contract about names. Four adjacent longs, three plausible at the same
    /// magnitude, so a positional construction reports word bytes as the byte count.</remarks>
    [Fact]
    public void AResultRoundTripsThroughTheDefaultConverter()
    {
        var converter = DataConverter.Default.PayloadConverter;
        var before = new FileScanResult(
            Rows: Rows100Mb,
            Bytes: Bytes100Mb,
            IndexSum: IndexSum100Mb,
            WordByteSum: WordByteSum100Mb,
            Verified: true);

        var after = converter.ToValue<FileScanResult>(converter.ToPayload(before));

        Assert.Equal(before, after);
        Assert.True(after.Verified);
    }
}
