using System.Text;
using Repro.Core;
using Repro.Core.Activities;
using Temporalio.Converters;
using Xunit;

namespace Repro.Tests;

/// <summary>
/// The pure statics <c>FileScanActivities</c> exposes, and the corpus arithmetic the whole
/// resume half of the case rests on.
/// </summary>
/// <remarks>
/// Every failure covered here is SILENT. The row parser returning a plausible index for a
/// structurally wrong row drifts the byte cursor without raising anything; a checkpoint that
/// disagrees with itself produces a wrong TOTAL five minutes later rather than an error; and a
/// checkpoint from a different corpus produces a wrong total that looks entirely plausible and
/// is reported as <c>outcome="completed"</c>.
/// <para>
/// The four functions under test are <c>public static</c> and pure precisely so this file can
/// exist: no <c>ActivityEnvironment</c>, no worker, no server, and -- see the corpus constants
/// below -- no filesystem. That is the <c>WeatherActivities.IsTransportFailure</c> precedent,
/// and <c>WeatherActivitiesTests</c>' remarks state the general form of the argument.
/// </para>
/// <para>
/// NOTHING HERE OPENS <c>sample_files/</c>. Read the remarks on <see cref="Rows100Mb"/> before
/// adding a test that does.
/// </para>
/// </remarks>
public class FileScanActivitiesTests
{
    // ---------------------------------------------------------------------------------
    // The committed corpora, DUPLICATED from scripts/gen-samples/MANIFEST.txt.
    // ---------------------------------------------------------------------------------

    /// <summary>Rows in <c>sample-100mb.txt</c>, per scripts/gen-samples/MANIFEST.txt.</summary>
    /// <remarks>
    /// DUPLICATED BY HAND, and no test in this file stats or reads the corpus. sample_files/ is
    /// gitignored and generated by scripts/gen-samples/gen-samples.sh, so it is ABSENT on a
    /// fresh clone: a test that read it would fail <c>dotnet test</c> for everybody who has not
    /// yet generated 1.15 GB of sample data, which is the same reason
    /// <c>ConfigLoader.ValidateFileScan</c> is forbidden from stating the file.
    /// <para>
    /// Same shape as <c>HistogramBucketsTests.HeartbeatTimeoutMs</c>, which duplicates
    /// <c>history.workflowTaskHeartbeatTimeout</c> out of
    /// observability/dynamicconfig/development-sql.yaml rather than parsing a file this process
    /// does not read. MANIFEST.txt is the record on the generator's side; keep the pair in step
    /// by hand, and note that <c>ConfigLoader.LargestShippedCorpusRows</c> is a third copy of
    /// the same table's last row.
    /// </para>
    /// </remarks>
    private const long Rows100Mb = 1_724_588;

    /// <inheritdoc cref="Rows100Mb"/>
    private const long Bytes100Mb = 99_999_968;

    /// <summary>digits(<see cref="Rows100Mb"/>) + 1, the length of line 1 including its LF.</summary>
    private const int Header100Mb = 8;

    /// <summary><see cref="Rows100Mb"/> x (<see cref="Rows100Mb"/> + 1) / 2, at a full scan.</summary>
    /// <remarks>
    /// The number the idempotency verdict is decided on, quoted as a literal in
    /// FileScanJob.cs, config.yaml, docs/WORKFLOWS.md and the plan's console transcript.
    /// </remarks>
    private const long IndexSum100Mb = 1_487_102_747_166;

    /// <summary><see cref="Bytes100Mb"/> - <see cref="Header100Mb"/> - 20 x <see cref="Rows100Mb"/>.</summary>
    private const long WordByteSum100Mb = 65_508_200;

    /// <summary><c>sample-200mb.txt</c>, the nearest neighbour a stale checkpoint can come from.</summary>
    /// <inheritdoc cref="Rows100Mb"/>
    private const long Rows200Mb = 3_449_054;

    /// <inheritdoc cref="Rows200Mb"/>
    private const long Bytes200Mb = 199_999_981;

    /// <summary>A mid-scan row on the 100 MB corpus, from the plan's RESUMING transcript line.</summary>
    private const long MidRows = 611_402;

    /// <inheritdoc cref="MidRows"/>
    private const long MidByteOffset = 35_461_940;

    /// <summary><see cref="MidByteOffset"/> - <see cref="Header100Mb"/> - 20 x <see cref="MidRows"/>.</summary>
    private const long MidWordByteSum = 23_233_892;

    /// <summary><see cref="MidRows"/> x (<see cref="MidRows"/> + 1) / 2.</summary>
    private const long MidIndexSum = 186_906_508_503;

    /// <summary>A fixed, NON-default heartbeat timestamp. See <see cref="Recorded"/>'s remarks.</summary>
    /// <remarks>
    /// Sub-second ticks on purpose: <c>DateTimeOffset</c> is the one field in the checkpoint
    /// whose round trip through the data converter loses precision if the converter is ever
    /// reconfigured, and truncation to whole seconds would pass a test written against a whole
    /// second. It must also never be <c>default</c>, which is the value
    /// <c>CheckpointDisagreement</c> treats as an unbound parameter.
    /// </remarks>
    private static readonly DateTimeOffset Recorded =
        new DateTimeOffset(2026, 9, 2, 10, 43, 17, TimeSpan.Zero).AddTicks(1_234_567);

    /// <summary>A checkpoint the shipped 100 MB scan really could have written, mid-file.</summary>
    /// <remarks>
    /// Built with NAMED arguments, the rule FileScanJob.cs states for this record: six longs in
    /// a row, of which three are large and plausible at the same magnitude, so a positional
    /// construction compiles clean and means something else entirely.
    /// </remarks>
    private static FileScanCheckpoint MidScan() => new(
        Rows: MidRows,
        ByteOffset: MidByteOffset,
        IndexSum: MidIndexSum,
        WordByteSum: MidWordByteSum,
        FileRows: Rows100Mb,
        FileBytes: Bytes100Mb,
        RecordedAtUtc: Recorded);

    /// <summary>The checkpoint an attempt writes after reading the LAST row of the corpus.</summary>
    /// <remarks>
    /// Reachable, not hypothetical: an attempt that read row N, heartbeated, and was killed
    /// before its result reached the server leaves exactly this. It is the boundary case
    /// <c>CorpusDisagreement</c>'s <c>&lt;=</c> comparisons exist for.
    /// </remarks>
    private static FileScanCheckpoint FullScan() => new(
        Rows: Rows100Mb,
        ByteOffset: Bytes100Mb,
        IndexSum: IndexSum100Mb,
        WordByteSum: WordByteSum100Mb,
        FileRows: Rows100Mb,
        FileBytes: Bytes100Mb,
        RecordedAtUtc: Recorded);

    // ---------------------------------------------------------------------------------
    // ParseRowIndex. The per-row hot path, and the byte cursor's only structural guard.
    // ---------------------------------------------------------------------------------

    /// <summary>A well-formed row yields its own 1-based index.</summary>
    /// <remarks>
    /// The LF is EXCLUDED, exactly as the read loop slices the row out from between two line
    /// breaks. Row 1 and row N are both here because the index is zero-padded to 10 digits and
    /// a parser that stopped at the first non-zero, or that skipped leading zeros by starting
    /// its loop at the wrong offset, gets row 1 right and row N wrong.
    /// </remarks>
    [Theory]
    [InlineData("0000000001 [ab abc abcd abcde ab abc abcd]", 1L)]
    [InlineData("0000000005 [aa bb cc dd ee ff gg]", 5L)]
    [InlineData("0000611402 [aa bb cc dd ee ff gg]", 611_402L)]
    [InlineData("0001724588 [aa bb cc dd ee ff gg]", 1_724_588L)]
    [InlineData("9999999999 [aa bb cc dd ee ff gg]", 9_999_999_999L)]
    public void ParsesAWellFormedRow(string row, long expected) =>
        Assert.Equal(expected, FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes(row)));

    /// <summary>Every structurally wrong shape returns the sentinel, never a plausible index.</summary>
    /// <remarks>
    /// A TOLERATED malformed row is the failure this guards, and it does not look like a
    /// failure. The word-byte accumulator is <c>rowLength + 1 - RowOverhead</c> whatever the row
    /// contains, so a row the parser accepted but should not have keeps the byte cursor moving
    /// and the checkpoint self-consistent; the only symptom is a resume, several hundred
    /// thousand rows later, that lands mid-row.
    /// <para>
    /// The <c>\r</c> row is the load-bearing one. The read loop splits on LF, so on a CRLF
    /// corpus the last byte of every row is <c>\r</c> rather than <c>]</c>. Rejecting it fails
    /// on row 1, loudly; tolerating it is the <c>line.Length + 1</c> failure mode -- one byte of
    /// cursor drift per row and no exception anywhere.
    /// </para>
    /// <para>
    /// MEASURED: deleting the <c>row[^1] != ']'</c> clause from <c>ParseRowIndex</c> left the
    /// whole suite green except three rows here -- <c>\r</c>, <c>\n</c> and <c>}</c>. Nothing
    /// else in the repo can see that clause go, which is what makes the CRLF row worth its
    /// line.
    /// </para>
    /// </remarks>
    [Theory]
    // Below the structural floor of 10 digits + ' ' + '[' + ']'. The second is the row one
    // byte short of legal, which is the boundary an off-by-one in the length check moves.
    [InlineData("")]
    [InlineData("0000000001")]
    [InlineData("0000000001 [")]
    // The separator after the index. A tab reads as whitespace to a human and to
    // long.TryParse, and as nothing at all to the corpus contract.
    [InlineData("0000000001\t[aa bb cc]")]
    [InlineData("0000000001_[aa bb cc]")]
    // The opening bracket. Round brackets are what a hand-edited fixture acquires.
    [InlineData("0000000001 (aa bb cc)")]
    [InlineData("0000000001  aa bb cc]")]
    // The closing bracket. CRLF FIRST: this is the whole reason the last byte is checked.
    [InlineData("0000000001 [aa bb cc]\r")]
    // And the LF itself, which pins the "row excludes its own LF" half of the contract: a
    // caller that sliced one byte too many is rejected rather than silently accepted.
    [InlineData("0000000001 [aa bb cc]\n")]
    [InlineData("0000000001 [aa bb cc}")]
    // The digits. A letter, a sign and a leading space are all accepted by long.TryParse and
    // all forbidden by the corpus contract, which is why ParseDigits is hand-rolled.
    [InlineData("000000000O [aa bb cc]")]
    [InlineData("+000000001 [aa bb cc]")]
    [InlineData("-000000001 [aa bb cc]")]
    [InlineData(" 000000001 [aa bb cc]")]
    // An 11-digit index, i.e. a corpus past 10^10 rows: the space lands one byte late.
    [InlineData("00000000012 [aa bb cc]")]
    public void RejectsAMalformedRow(string row) =>
        // The other direction -- that this is not simply a parser which rejects everything --
        // is ParsesAWellFormedRow above and AcceptsTheShortestStructurallyLegalRow below.
        Assert.Equal(
            FileScanActivities.MalformedRow,
            FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes(row)));

    /// <summary>A row with no words at all is LEGAL, and that is deliberate.</summary>
    /// <remarks>
    /// The length floor is the STRUCTURAL minimum -- 10 digits, a space, a bracket, a bracket --
    /// and not <c>RowOverhead</c>. Tightening it to <c>RowOverhead</c> looks like an
    /// improvement and is not: the word-byte accumulator is DEFINED as
    /// <c>rowLength + 1 - RowOverhead</c>, so a wordless row contributes a negative term and
    /// the offset identity still holds exactly. Rows in the shipped corpora are 41 to 76 bytes
    /// including the LF, so this shape never occurs there; it is pinned so that the floor is
    /// not "corrected" into rejecting a legal file.
    /// </remarks>
    [Fact]
    public void AcceptsTheShortestStructurallyLegalRow() =>
        Assert.Equal(1L, FileScanActivities.ParseRowIndex(Encoding.ASCII.GetBytes("0000000001 []")));

    /// <summary>The sentinel must stay outside the range of any real row index.</summary>
    /// <remarks>
    /// Row indices are 1-based, so <c>-1</c> can never be confused with one. If this ever
    /// became 0, the resume path's row-identity proof ("does this row carry index Rows + 1")
    /// would silently accept a malformed row as row 0 at the head of the file.
    /// </remarks>
    [Fact]
    public void TheMalformedSentinelCannotBeARowIndex() =>
        Assert.True(FileScanActivities.MalformedRow < 1);

    // ---------------------------------------------------------------------------------
    // HeaderLength. Pure arithmetic, and the one input to the byte identity that is DERIVED
    // rather than carried, so an error here moves every checkpoint's expected offset.
    // ---------------------------------------------------------------------------------

    /// <summary>digits(N) + 1, including the digit boundaries on both sides.</summary>
    /// <remarks>
    /// EVERY BOUNDARY IS HERE because the loop is <c>for (r = fileRows; r >= 10; r /= 10)</c>,
    /// and both plausible off-by-ones (<c>&gt;</c> for <c>&gt;=</c>, or seeding <c>digits</c> at
    /// 0) are correct on a mid-decade number and wrong at exactly one power of ten. The cost is
    /// not a bad message: <c>headerLen</c> is a term in
    /// <c>ByteOffset == headerLen + 20 x Rows + WordByteSum</c>, so one byte of error rejects
    /// EVERY legitimate checkpoint -- and it rejects them as terminal, so the workflow fails
    /// permanently and reads as "resume is broken".
    /// <para>
    /// MEASURED, and this is why the powers of ten are not padding: changing the loop's
    /// <c>remaining &gt;= 10</c> to <c>remaining &gt; 10</c> fails exactly four rows here -- 10,
    /// 100, 1000 and 1,000,000 -- and leaves ALL FOUR shipped-corpus rows passing, because
    /// 1,724,588 comes out right under both. Nothing else in the suite moved. A table of
    /// realistic corpus sizes would not have seen it.
    /// </para>
    /// </remarks>
    [Theory]
    [InlineData(1L, 2)]
    [InlineData(9L, 2)]
    [InlineData(10L, 3)]
    [InlineData(11L, 3)]
    [InlineData(99L, 3)]
    [InlineData(100L, 4)]
    [InlineData(999L, 4)]
    [InlineData(1000L, 5)]
    [InlineData(999_999L, 7)]
    [InlineData(1_000_000L, 8)]
    // The four shipped corpora. All four are 7 digits, which is exactly why the corpus
    // discriminator is (fileRows, fileBytes) and not the header length.
    [InlineData(Rows100Mb, 8)]
    [InlineData(Rows200Mb, 8)]
    [InlineData(6_035_691L, 8)]
    [InlineData(8_622_570L, 8)]
    public void HeaderLengthIsDigitsPlusTheLineFeed(long fileRows, int expected) =>
        Assert.Equal(expected, FileScanActivities.HeaderLength(fileRows));

    /// <summary>Zero rows still costs a digit and an LF, so the seek-back cannot go negative.</summary>
    /// <remarks>
    /// <c>CheckpointDisagreement</c> rejects a zero <c>FileRows</c> outright, so this value is
    /// never used in anger -- it is pinned because the line-boundary proof seeks to
    /// <c>ByteOffset - 1</c>, and the chain that keeps that non-negative is
    /// <c>ByteOffset &gt;= headerLen &gt;= 2</c>. A <c>HeaderLength</c> that could return 0 or
    /// 1 would turn a malformed checkpoint into an <c>ArgumentOutOfRangeException</c> out of
    /// <c>FileStream.Seek</c>, which is retryable and would burn all ten attempts.
    /// </remarks>
    [Fact]
    public void HeaderLengthIsNeverBelowTwo() =>
        Assert.Equal(2, FileScanActivities.HeaderLength(0));

    // ---------------------------------------------------------------------------------
    // CheckpointDisagreement. No I/O: everything it checks is carried in the checkpoint.
    // ---------------------------------------------------------------------------------

    /// <summary>A checkpoint the scan really wrote passes, mid-file and at the end.</summary>
    /// <remarks>
    /// The direction that matters most, because <c>CheckpointDisagreement</c> failing is
    /// TERMINAL: a rule that is too strict does not degrade the case, it fails the workflow
    /// non-retryably on a perfectly good checkpoint, which reads as "resume is broken" -- the
    /// worst way for this case to fail.
    /// </remarks>
    [Fact]
    public void AcceptsASelfConsistentCheckpoint()
    {
        Assert.Null(FileScanActivities.CheckpointDisagreement(MidScan()));
        Assert.Null(FileScanActivities.CheckpointDisagreement(FullScan()));
    }

    /// <summary>Row 0 at the header offset is self-consistent, and must not need a special case.</summary>
    /// <remarks>
    /// The uniformity the line-boundary proof depends on: at <c>Rows == 0</c> the offset is the
    /// header length and the byte at <c>ByteOffset - 1</c> is line 1's own LF, so there is no
    /// at-the-start branch anywhere in the resume path. If this were rejected, the branch would
    /// have to be reintroduced, and an untested branch on the resume path is the last thing
    /// this case needs.
    /// </remarks>
    [Fact]
    public void AcceptsTheZeroRowCheckpoint() =>
        Assert.Null(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: 0,
            ByteOffset: Header100Mb,
            IndexSum: 0,
            WordByteSum: 0,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));

    /// <summary>THE SCHEMA-DRIFT SIGNATURE: a zeroed IndexSum beside a correct ByteOffset.</summary>
    /// <remarks>
    /// This is the one row in this file that is not a hypothetical. Heartbeat details bind by
    /// NAME through the data converter, so renaming a <c>FileScanCheckpoint</c> parameter binds
    /// nothing and yields <c>default(T)</c> for it -- and every OTHER field still arrives
    /// correct, so the checkpoint deserializes with no error, the byte cursor is right, the
    /// resume seeks to a real line boundary, the row-identity proof passes, and the scan runs
    /// to completion reporting a total that is short by exactly the rows before the checkpoint.
    /// <para>
    /// Without this check the only symptom is <c>repro_file_scan_verified{result="mismatch"}</c>
    /// five minutes later at completion, which sends the reader after a resume bug that does not
    /// exist. <see cref="ARenamedParameterBindsNothingAndTheDriftCheckCatchesIt"/> drives the
    /// same case through the real converter rather than constructing the drifted record by hand.
    /// </para>
    /// <para>
    /// MEASURED: neutering the <c>IndexSum != expectedIndexSum</c> branch in
    /// <c>CheckpointDisagreement</c> fails exactly five tests, all of them in this file -- this
    /// one, all three rows of <see cref="RejectsAnIndexSumThatIsNotTheClosedForm"/>, and
    /// <see cref="ARenamedParameterBindsNothingAndTheDriftCheckCatchesIt"/>. The other 222
    /// stayed green, including every test that touches the byte identity: the offset arithmetic
    /// cannot see this failure, which is the definition of the hole.
    /// </para>
    /// </remarks>
    [Fact]
    public void RejectsAZeroedIndexSumBesideACorrectByteOffset()
    {
        var drifted = MidScan() with { IndexSum = 0 };

        // The byte cursor is untouched and still agrees with itself, which is what makes this
        // silent: the offset identity CANNOT see this failure.
        Assert.Equal(
            FileScanActivities.HeaderLength(drifted.FileRows)
                + (FileScanActivities.RowOverhead * drifted.Rows)
                + drifted.WordByteSum,
            drifted.ByteOffset);

        var why = FileScanActivities.CheckpointDisagreement(drifted);

        Assert.NotNull(why);
        Assert.Contains("indexSum", why!, StringComparison.Ordinal);
    }

    /// <summary>A zeroed FileRows or FileBytes is the same unbound-parameter failure.</summary>
    /// <remarks>
    /// Checked FIRST in production because everything below it derives the header length from
    /// <c>FileRows</c>: at zero, <c>HeaderLength</c> returns 2 and the byte identity is then
    /// evaluated against a header length no corpus has, so the message would blame the offset
    /// for a failure that is really a missing field.
    /// </remarks>
    [Fact]
    public void RejectsACheckpointWithNoCorpusIdentity()
    {
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileRows = 0 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileBytes = 0 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileRows = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { FileBytes = -1 }));
    }

    /// <summary>None of the three accumulators may be negative.</summary>
    /// <remarks>
    /// All three are monotone over a forward scan, so a negative value is impossible in a
    /// checkpoint this scan wrote. The specific cost of not checking is on the SEEK: the chain
    /// that keeps <c>Seek(ByteOffset - 1)</c> non-negative is the byte identity plus
    /// non-negative <c>Rows</c> and <c>WordByteSum</c>, and dropping either bound admits a
    /// negative offset that fails inside <c>FileStream</c> as a retryable exception, burning
    /// all ten attempts on a checkpoint that can never work.
    /// </remarks>
    [Fact]
    public void RejectsNegativeAccumulators()
    {
        // The negativity bound is checked BEFORE the byte identity, which is why each of these
        // moves one field and leaves the rest of the checkpoint alone: the point is that the
        // bound fires on its own account rather than being caught downstream by the offset
        // arithmetic, which would not fire for a negative WordByteSum paired with a
        // correspondingly small offset.
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { Rows = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { WordByteSum = -1 }));
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(MidScan() with { IndexSum = -1 }));

        // And the one that WOULD survive a byte-identity-only check: a negative word-byte sum
        // carried consistently in the offset. 8 + (20 x 0) + (-1) = 7, so the seek-back this
        // check protects would land at byte 6 of a file whose first row starts at byte 8.
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: 0,
            ByteOffset: Header100Mb - 1,
            IndexSum: 0,
            WordByteSum: -1,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));
    }

    /// <summary>A scan cannot have completed more rows than its own header declares.</summary>
    /// <remarks>
    /// Caught here rather than left to <c>CorpusDisagreement</c> because this one needs no file
    /// at all: it is the checkpoint contradicting itself. Left unchecked, the offset identity
    /// would put <c>ByteOffset</c> past the end of the corpus and the failure would surface as a
    /// seek past EOF -- an empty read the loop reports as a truncated file, blaming the corpus
    /// for the checkpoint's arithmetic.
    /// </remarks>
    [Fact]
    public void RejectsMoreCompletedRowsThanTheCorpusHas() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint(
            Rows: Rows100Mb + 1,
            ByteOffset: Bytes100Mb + 20,
            IndexSum: (Rows100Mb + 1) * (Rows100Mb + 2) / 2,
            WordByteSum: WordByteSum100Mb,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded)));

    /// <summary>The BYTE identity: one byte of drift in either direction is refused.</summary>
    /// <remarks>
    /// <c>ByteOffset == headerLen + 20 x Rows + WordByteSum</c> is what ties the accumulator to
    /// the BYTE cursor, where the closed form ties it to the ROW cursor. A resume bug that moved
    /// one and not the other shows up in exactly one of the two, which is why both are checked
    /// and why plus-one and minus-one are both here: the drift a <c>StreamReader</c> path
    /// produces is one byte PER ROW and starts as one byte.
    /// </remarks>
    [Theory]
    [InlineData(1L)]
    [InlineData(-1L)]
    [InlineData(20L)]
    public void RejectsAByteOffsetThatDisagreesWithItsOwnRowCount(long drift)
    {
        var why = FileScanActivities.CheckpointDisagreement(
            MidScan() with { ByteOffset = MidByteOffset + drift });

        Assert.NotNull(why);
        Assert.Contains("byte offset", why!, StringComparison.Ordinal);
    }

    /// <summary>The ROW identity: an IndexSum that is not the closed form for its own row count.</summary>
    /// <remarks>
    /// The generalisation of <see cref="RejectsAZeroedIndexSumBesideACorrectByteOffset"/>: any
    /// value other than <c>Rows x (Rows + 1) / 2</c> means the accumulator and the row cursor
    /// were not written from the same batch, and the rule that generalises is that THE
    /// ACCUMULATOR'S ORIGIN AND THE READ CURSOR'S ORIGIN MUST BE THE SAME CHECKPOINT. A
    /// checkpoint that violates it is not repairable at resume time, only refusable.
    /// </remarks>
    [Theory]
    [InlineData(1L)]
    [InlineData(-1L)]
    [InlineData(611_402L)]  // off by one row's worth: a resume that counted its landing row twice
    public void RejectsAnIndexSumThatIsNotTheClosedForm(long drift) =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(
            MidScan() with { IndexSum = MidIndexSum + drift }));

    /// <summary>A default RecordedAtUtc is refused, and the cost is the staleness histogram.</summary>
    /// <remarks>
    /// The same unbound-parameter failure as the zeroed <c>FileRows</c>, with a different and
    /// oddly specific symptom: <c>DateTimeOffset.default</c> is year 1, so
    /// <c>now - RecordedAtUtc</c> records a two-thousand-year staleness into
    /// <c>repro_file_scan_staleness</c>, whose top boundary is 90 seconds. Every such sample
    /// lands in <c>+Inf</c>, so p95 reads as the top boundary forever and the 24s throttle
    /// shoulder the row exists to show is gone.
    /// </remarks>
    [Fact]
    public void RejectsACheckpointWithNoTimestamp() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(
            MidScan() with { RecordedAtUtc = default }));

    /// <summary>An all-default checkpoint -- what a wholly unbound payload yields -- is refused.</summary>
    /// <remarks>
    /// Every parameter of <c>FileScanCheckpoint</c> is defaulted, which is what lets a history
    /// captured before a field existed still deserialize. The other side of that is that a
    /// payload which binds NOTHING deserializes silently into this value rather than throwing,
    /// so it has to be refused explicitly.
    /// </remarks>
    [Fact]
    public void RejectsTheAllDefaultCheckpoint() =>
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(new FileScanCheckpoint()));

    // ---------------------------------------------------------------------------------
    // CorpusDisagreement. Self-consistency is NOT enough: the checkpoint has to be about
    // the file that is now open, and inside this invocation's bounds.
    // ---------------------------------------------------------------------------------

    /// <summary>
    /// THE PLAUSIBLE WRONG ANSWER: a perfectly self-consistent 200 MB checkpoint against the
    /// 100 MB file.
    /// </summary>
    /// <remarks>
    /// The checkpoint below is real -- it is what a scan of sample-200mb.txt writes at row
    /// 1,200,000 -- and it passes <c>CheckpointDisagreement</c> completely, which is the point:
    /// SELF-CONSISTENCY CANNOT SEE A CORPUS SWAP. Both corpora have a 7-digit header, so even
    /// the derived header length matches. gen_samples.py keys its word seed on TARGET SIZE, so
    /// the two files are independent streams that happen to share a format.
    /// <para>
    /// Without this check the resume seeks to byte 69,576,008 of the 100 MB file, lands on a
    /// valid line boundary, and the row-identity proof compares the landing row's index against
    /// <c>Rows + 1</c> -- which is a property of the OFFSET, not of the corpus, so it can pass.
    /// The scan then runs to completion, reports <c>outcome="completed"</c>, and returns a sum
    /// computed over a mixture of two files. The aggregate check would eventually notice, but it
    /// would blame the AGGREGATE, sending the reader after a resume bug instead of after "the
    /// corpus changed underneath you".
    /// </para>
    /// <para>
    /// MEASURED: neutering the <c>(fileRows, fileBytes)</c> comparison in
    /// <c>CorpusDisagreement</c> fails only this test and
    /// <see cref="RejectsAMismatchInEitherHalfOfTheCorpusIdentity"/>. Every checkpoint
    /// self-consistency test in this file stayed green, which is the measurement that matters:
    /// no amount of arithmetic on a checkpoint can tell you which file it came from.
    /// </para>
    /// </remarks>
    [Fact]
    public void RejectsASelfConsistentCheckpointFromADifferentCorpus()
    {
        var from200Mb = new FileScanCheckpoint(
            Rows: 1_200_000,
            ByteOffset: 69_576_008,
            IndexSum: 720_000_600_000,
            WordByteSum: 45_576_000,
            FileRows: Rows200Mb,
            FileBytes: Bytes200Mb,
            RecordedAtUtc: Recorded);

        // Self-consistent, and therefore invisible to every check that needs no file.
        Assert.Null(FileScanActivities.CheckpointDisagreement(from200Mb));

        // It even lands INSIDE the smaller corpus, so a bounds check alone would pass it too.
        Assert.True(from200Mb.ByteOffset < Bytes100Mb);

        var why = FileScanActivities.CorpusDisagreement(
            from200Mb, "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb);

        Assert.NotNull(why);

        // The message must name BOTH shapes, because the whole value of catching it here rather
        // than at the aggregate is that the reader is told which two files disagree.
        Assert.Contains("/corpus/sample-100mb.txt", why!, StringComparison.Ordinal);
        Assert.Contains("3449054", why!, StringComparison.Ordinal);
        Assert.Contains("1724588", why!, StringComparison.Ordinal);
    }

    /// <summary>The matching corpus is accepted, mid-scan and at the last row.</summary>
    /// <remarks>
    /// The last-row case is the reason the bounds are <c>&lt;=</c> and not <c>&lt;</c>, and it
    /// is reachable: an attempt that read row N, heartbeated, and was killed before its result
    /// reached the server leaves <c>Rows == rowsToScan</c> and <c>ByteOffset == fileBytes</c>.
    /// Rejecting that would fail the workflow terminally FOR HAVING FINISHED.
    /// </remarks>
    [Fact]
    public void AcceptsACheckpointForTheFileThatIsOpen()
    {
        Assert.Null(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));

        Assert.Null(FileScanActivities.CorpusDisagreement(
            FullScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));
    }

    /// <summary>Either half of the identity pair is enough to refuse the resume.</summary>
    /// <remarks>
    /// Both halves are asserted separately because a regenerated corpus of a DIFFERENT target
    /// size differs in both numbers, so a check that tested only one would still pass the
    /// shipped cases and would be blind to a truncated or appended file -- same row count, more
    /// bytes, or the reverse.
    /// </remarks>
    [Fact]
    public void RejectsAMismatchInEitherHalfOfTheCorpusIdentity()
    {
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/x.txt", Rows100Mb + 1, Bytes100Mb, Rows100Mb));

        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/x.txt", Rows100Mb, Bytes100Mb + 1, Rows100Mb));
    }

    /// <summary>A checkpoint written under a larger maxRows is a DIFFERENT JOB.</summary>
    /// <remarks>
    /// The same file, the same format, an offset well inside it -- and resuming from it would
    /// report a total for a question nobody asked. The completion aggregate is
    /// <c>rowsToScan x (rowsToScan + 1) / 2</c>, so a checkpoint from a bigger job carries an
    /// <c>IndexSum</c> already past that target and the scan would fail
    /// <c>result="mismatch"</c> at the end: the one failure this case must never produce
    /// spuriously.
    /// </remarks>
    [Fact]
    public void RejectsACheckpointFromALargerJob() =>
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            MidScan(), "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, rowsToScan: 500_000));

    /// <summary>An offset past EOF on a file whose identity MATCHED is still refused.</summary>
    /// <remarks>
    /// Unreachable-looking and cheap to keep: the corpus identity has already matched, so this
    /// says the checkpoint's own arithmetic and the file disagree. Without it the resume seeks
    /// past EOF, the fill returns zero bytes, and the loop reports a truncated corpus -- blaming
    /// the file for the checkpoint.
    /// </remarks>
    [Fact]
    public void RejectsAnOffsetPastTheEndOfAMatchingFile()
    {
        // Self-consistent by construction: the extra word bytes are carried in the offset.
        var past = new FileScanCheckpoint(
            Rows: Rows100Mb,
            ByteOffset: Bytes100Mb + 1000,
            IndexSum: IndexSum100Mb,
            WordByteSum: WordByteSum100Mb + 1000,
            FileRows: Rows100Mb,
            FileBytes: Bytes100Mb,
            RecordedAtUtc: Recorded);

        Assert.Null(FileScanActivities.CheckpointDisagreement(past));
        Assert.NotNull(FileScanActivities.CorpusDisagreement(
            past, "/corpus/sample-100mb.txt", Rows100Mb, Bytes100Mb, Rows100Mb));
    }

    // ---------------------------------------------------------------------------------
    // The three closed forms, against the real committed corpus numbers. PURE ARITHMETIC.
    // ---------------------------------------------------------------------------------

    /// <summary><c>IndexSum == N x (N + 1) / 2</c> for the shipped 100 MB corpus.</summary>
    /// <remarks>
    /// 1,487,102,747,166 is quoted as a LITERAL in FileScanJob.cs, config.yaml,
    /// docs/WORKFLOWS.md and the plan's console transcript, and it is the number the idempotency
    /// verdict is decided on. This is what makes a MANIFEST.txt regeneration that changes N a
    /// test failure rather than four stale literals and a scan that reports
    /// <c>result="mismatch"</c> against a correct read.
    /// <para>
    /// Also pins that the product does not overflow: N x (N + 1) is 2.97e12, which is fine in
    /// <c>long</c> and would silently wrap in <c>int</c>.
    /// </para>
    /// </remarks>
    [Fact]
    public void TheFullScanIndexSumIsTheDocumentedConstant() =>
        Assert.Equal(IndexSum100Mb, Rows100Mb * (Rows100Mb + 1) / 2);

    /// <summary><c>WordByteSum == FileBytes - HeaderLen - 20 x N</c>.</summary>
    /// <remarks>
    /// The second, INDEPENDENT witness, and the one that ties the answer to the byte cursor.
    /// Written through <c>HeaderLength</c> and <c>RowOverhead</c> rather than through the
    /// literals 8 and 20, so a change to either constant fails here against MANIFEST.txt's
    /// numbers instead of at the end of a five-minute scan.
    /// </remarks>
    [Fact]
    public void TheFullScanWordByteSumIsTheDocumentedConstant() =>
        Assert.Equal(
            WordByteSum100Mb,
            Bytes100Mb
                - FileScanActivities.HeaderLength(Rows100Mb)
                - (FileScanActivities.RowOverhead * Rows100Mb));

    /// <summary>The offset identity, at completion AND mid-scan.</summary>
    /// <remarks>
    /// <c>ByteOffset == HeaderLen + 20 x Rows + WordByteSum</c> holds at EVERY checkpoint, not
    /// just at the end, and the mid-scan case is the one resume depends on. At completion it
    /// degenerates into <c>endOffset == fileBytes</c>, which is the second half of the
    /// completion check -- so the two assertions here are the same statement of the corpus
    /// contract read at two different points in the scan.
    /// </remarks>
    [Fact]
    public void TheOffsetIdentityHoldsAtEveryCheckpoint()
    {
        Assert.Equal(
            Bytes100Mb,
            FileScanActivities.HeaderLength(Rows100Mb)
                + (FileScanActivities.RowOverhead * Rows100Mb)
                + WordByteSum100Mb);

        Assert.Equal(
            MidByteOffset,
            FileScanActivities.HeaderLength(Rows100Mb)
                + (FileScanActivities.RowOverhead * MidRows)
                + MidWordByteSum);
    }

    /// <summary>The fixed row overhead is the one gen_samples.py writes.</summary>
    /// <remarks>
    /// 10 index digits + one space + <c>[</c> + six inner separators + <c>]</c> + LF = 20,
    /// matching <c>ROW_OVERHEAD</c> at scripts/gen-samples/gen_samples.py:48. It is the
    /// coefficient in both identities above, so it cannot be adjusted on either side alone: a
    /// generator that emitted a different fixed part would make every checkpoint this scan
    /// writes fail its own byte identity.
    /// </remarks>
    [Fact]
    public void RowOverheadMatchesTheGenerator()
    {
        Assert.Equal(20, FileScanActivities.RowOverhead);
        Assert.Equal(10, FileScanActivities.IndexDigits);
    }

    // ---------------------------------------------------------------------------------
    // The data converter. PINNED, not argued.
    // ---------------------------------------------------------------------------------

    /// <summary>A checkpoint survives the default payload converter, field for field.</summary>
    /// <remarks>
    /// PINNED RATHER THAN REASONED ABOUT, because a data-converter failure on heartbeat details
    /// does not arrive as an error. The conversion cancels the activity with
    /// <c>ActivityCancelReason.HeartbeatRecordFailure</c> and then fails it, so the symptom on
    /// the board is a cancellation -- indistinguishable at a glance from a worker drain, which is
    /// a thing this case does on purpose.
    /// <para>
    /// Six longs and a <c>DateTimeOffset</c> is about 100 bytes against a 2 MB default payload
    /// limit, so size is not the risk. The risks are precision (hence the sub-second ticks on
    /// <see cref="Recorded"/>) and binding, which the next test covers.
    /// </para>
    /// </remarks>
    [Fact]
    public void ACheckpointRoundTripsThroughTheDefaultConverter()
    {
        var converter = DataConverter.Default.PayloadConverter;
        var before = MidScan();

        var after = converter.ToValue<FileScanCheckpoint>(converter.ToPayload(before));

        // Record equality is structural, so this covers all seven fields at once.
        Assert.Equal(before, after);

        // And the round trip must not merely be equal, it must still be RESUMABLE: this is the
        // assertion that would fail if the converter ever started truncating a long or dropping
        // sub-second ticks, both of which leave a checkpoint that looks fine field by field.
        Assert.Null(FileScanActivities.CheckpointDisagreement(after));
        Assert.Equal(Recorded, after.RecordedAtUtc);
    }

    /// <summary>A RENAMED parameter binds nothing, yields default(T), and is caught.</summary>
    /// <remarks>
    /// The schema-drift failure driven through the REAL converter rather than constructed by
    /// hand, which is what makes it evidence rather than a restatement of
    /// <see cref="RejectsAZeroedIndexSumBesideACorrectByteOffset"/>. The payload here carries
    /// <c>IndexSumTotal</c> where the record declares <c>IndexSum</c> -- the single-word rename
    /// a tidy-up produces -- and everything else is spelled correctly.
    /// <para>
    /// MEASURED with this exact payload: <c>Rows</c>, <c>ByteOffset</c>, <c>WordByteSum</c>,
    /// <c>FileRows</c>, <c>FileBytes</c> and <c>RecordedAtUtc</c> all bind correctly and
    /// <c>IndexSum</c> comes back 0, with NO exception from the converter. That is what a silent
    /// wrong answer looks like at the point it is created.
    /// </para>
    /// </remarks>
    [Fact]
    public void ARenamedParameterBindsNothingAndTheDriftCheckCatchesIt()
    {
        var converter = DataConverter.Default.PayloadConverter;

        var drifted = converter.ToValue<FileScanCheckpoint>(converter.ToPayload(new
        {
            Rows = MidRows,
            ByteOffset = MidByteOffset,
            IndexSumTotal = MidIndexSum,   // <- the rename
            WordByteSum = MidWordByteSum,
            FileRows = Rows100Mb,
            FileBytes = Bytes100Mb,
            RecordedAtUtc = Recorded,
        }));

        // EVERY OTHER FIELD ARRIVES CORRECT. Without these, a converter that bound nothing at
        // all would pass the assertion below for entirely the wrong reason, and this test would
        // stop being about a rename.
        Assert.Equal(MidRows, drifted.Rows);
        Assert.Equal(MidByteOffset, drifted.ByteOffset);
        Assert.Equal(MidWordByteSum, drifted.WordByteSum);
        Assert.Equal(Rows100Mb, drifted.FileRows);
        Assert.Equal(Bytes100Mb, drifted.FileBytes);
        Assert.Equal(Recorded, drifted.RecordedAtUtc);

        // The renamed one is default(long), and the converter raised nothing.
        Assert.Equal(0L, drifted.IndexSum);

        // Which is precisely the case CheckpointDisagreement exists to refuse.
        Assert.NotNull(FileScanActivities.CheckpointDisagreement(drifted));
    }

    /// <summary>The RESULT record round-trips too, since it is a replay-visible schema.</summary>
    /// <remarks>
    /// An activity's return value lands in the history and is read back on replay, so its shape
    /// is a contract about NAMES. The hazard specific to <c>FileScanResult</c> is four adjacent
    /// longs, three of which are plausible at the same magnitude for the 100 MB corpus
    /// (99,999,968 bytes against 65,508,200 word bytes), so a positional construction compiles
    /// clean and reports the word-byte sum as the byte count. Named arguments here, and the
    /// round trip pins that the names are what travel.
    /// </remarks>
    [Fact]
    public void AResultRoundTripsThroughTheDefaultConverter()
    {
        var converter = DataConverter.Default.PayloadConverter;
        var before = new FileScanResult(
            Rows: Rows100Mb,
            Bytes: Bytes100Mb,
            IndexSum: IndexSum100Mb,
            WordByteSum: WordByteSum100Mb,
            Verified: true);

        var after = converter.ToValue<FileScanResult>(converter.ToPayload(before));

        Assert.Equal(before, after);
        Assert.True(after.Verified);
    }
}
